### ISSUE TITLE
Potential Typo in Textbook (Page 9)

### ISSUE THREAD

**Issue by Shoooooon** [lorisdanto/cs703-program-synthesis#1]
Hi. Should Example 2.1.3 read "and E_𝐼𝐷(t) returns true only when 𝑡 is an expression computing the identity" instead of "and E_𝐼𝐷(𝑒) returns true only when 𝑡 is an expression computing the identity"?

Similarly, on Page 10, E(𝑒^∗) is used rather than E(t^*) in list item 2.

**Comment by jinsooihm** [comment]
There is a similar potential typo in page 13 section 2.2.2.

**Comment by lorisdanto** [comment]
Fixed thanks. Will appear in updated version
