### ISSUE TITLE
Typos in the textbook page 12~13

### ISSUE THREAD

**Issue by jinsooihm** [lorisdanto/cs703-program-synthesis#2]
Hello,

It seems there are some typos in the book page 12~13 in section 2.2.1 Semantics for STRINGY.

For example, in the third definition for concatenation, it says 
$[[s_1 ++ s_2]]_S(str) = [[s_1]]_S(x) ++ [[s_1]]_S(x)$,
but I think it should be
$[[s_1 ++ s_2]]_S(str) = [[s_1]]_S(str) ++ [[s_2]_S(str)$,
so changing $x$ to $str$ and the second $s_1$ to $s_2$.

In the fourth definition, there is a similar problem with $n_1$ and $n_2$.

In the fifth definition, I believe $find$ should be wrapped around by $[[ \cdot ]]_N$ instead of $[[ \cdot ]]_S$.

**Comment by lorisdanto** [comment]
Fixed thanks! It will appear in the updated version soon
