### ISSUE TITLE
Typos in page 15

### ISSUE THREAD

**Issue by jinsooihm** [lorisdanto/cs703-program-synthesis#3]
Hello,

In the definition of the teacher $T = (M, E)$ in section 2.3.2 page 15,
the second bullet seems to be missing $t^*$ in the semantics square brackets.

It currently says $\psi(x,y) \wedge [[(]]x) \ne y$ and $\psi(i,o) \wedge [[(]]i) \ne o$,
but I believe it should be something like $\psi(x,y) \wedge [[t^\ast]] (x) \ne y$ and $\psi(i,o) \wedge [[ t^\ast ]] (i) \ne o$,

**Comment by lorisdanto** [comment]
Fixed thanks. Will appear in updated version
