### ISSUE TITLE
Lemma 2.1.4 in Book

### ISSUE THREAD

**Issue by Shoooooon** [lorisdanto/cs703-program-synthesis#4]
Hi,

Lemma 2.1.4 may be missing a hypothesis. One can construct a counterexample by considering a total order which is not enumerable (e.g., even programs and odd programs are compared to one another by length, but even programs are considered greater than odd programs).

Some ways to resolve this might be:
- Specify that the total order is induced by an enumeration of expressions.
- Demand that the total order is such that any expression is greater than at most finitely many elements, which would I think be equivalent to enumerability (given that the total order is computable).

We also require the total order to be computable, but the first of the two additional hypotheses above should imply computability of the relation.

**Comment by lorisdanto** [comment]
Thanks. The condition you describe is that the order has no "infinite descending chains".
I fixed for the next iteration!
